name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Stats Card
        uses: lowlighter/metrics@latest
        with:
          filename: stats/github-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AmitKumar-24
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

  generate-languages:
    runs-on: ubuntu-latest
    needs: generate-stats
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Pull latest changes
        run: git pull origin main

      - name: Generate Top Languages Card
        uses: lowlighter/metrics@latest
        with:
          filename: stats/top-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AmitKumar-24
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          config_timezone: Asia/Kolkata
